// Exercise the shipped client after the same keepNames transform Wrangler uses.
// Source-only execution misses helpers captured by Function.toString().
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { tmpdir } from 'node:os';
import { mkdtemp, rm } from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
const require = createRequire(path.join(process.env.NODE_PATH || path.resolve('node_modules'), 'test.cjs'));
const { build } = require('esbuild');
const { chromium } = require('playwright');
const dir = await mkdtemp(path.join(tmpdir(), 'workspace-browser-'));
let browser;
try {
 const outfile = path.join(dir, 'client.mjs');
 await build({entryPoints:[process.env.WORKSPACE_TEST_ENTRY || 'admin/workspace-client.js'],bundle:true,format:'esm',keepNames:true,outfile});
 const { WORKSPACE_CLIENT, WORKSPACE_CSS } = await import(pathToFileURL(outfile));
 browser = await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});
 const page = await browser.newPage({viewport:{width:1280,height:900}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 let failFeed=false, saved;
 const event={id:'n:7',source:'news',title:'Community meal',start:'2026-09-23T18:00:00',end:'2026-09-23T19:00:00',category:'special',description:'All welcome',location:'Hall'};
 const config={mode:'calendar',today:'2026-09-23',canAdd:true,canNews:true,rooms:['Hall'],types:[]};
 const html=()=>`<!doctype html>${WORKSPACE_CSS}<div id="workspace-calendar"></div><script id="workspace-data" type="application/json">${JSON.stringify(config)}</script><script>${WORKSPACE_CLIENT}</script>`;
 await page.route('https://workspace.test/**',async route=>{
  const url=new URL(route.request().url());
  if(url.pathname.endsWith('/feed'))return route.fulfill({status:failFeed?503:200,json:failFeed?{error:'Calendar unavailable.'}:{events:[event],categories:[{key:'special',name:'Special'}],google:true}});
  if(url.pathname.endsWith('/local')){saved=route.request().postDataJSON();return route.fulfill({json:{id:42}});}
  return route.fulfill({contentType:'text/html',body:html()});
 });
 await page.goto('https://workspace.test/calendar-workspace');
 assert.deepEqual(errors,[], 'Calendar script must boot after production bundling');
 await page.locator('.ws-day').first().waitFor();
 assert.ok(await page.locator('.ws-day').count()>=35);

 assert.match(await page.locator('[data-event="n:7"]').innerText(),/Special/);
 assert.doesNotMatch(await page.locator('[data-event="n:7"]').innerText(),/News & Events|Google Calendar/);
 await page.locator('#calendar-search').fill('missing event');
 assert.equal(await page.locator('[data-event="n:7"]').count(),0);
 await page.locator('#calendar-search').fill('community');
 assert.equal(await page.locator('[data-event="n:7"]').count(),1);
 await page.locator('#calendar-search').fill('');
 await page.locator('#calendar-category').selectOption('special');
 assert.equal(await page.locator('[data-event="n:7"]').count(),1);
 await page.locator('#calendar-category').selectOption('');
 await page.locator('[data-event="n:7"]').click();
 assert.equal(await page.locator('dialog a').getAttribute('href'),'/newsitems/edit/7');
 await page.getByRole('button',{name:'Close event panel'}).click();
 await page.locator('[data-add="2026-09-24"]').click();
 assert.equal(await page.locator('[name=date]').inputValue(),'2026-09-24');
 await page.locator('[name=title]').fill('Test local event');
 await page.getByRole('button',{name:'Add to public calendar'}).click();
 await page.getByText('Event saved to the public calendar.',{exact:false}).waitFor();
 assert.equal(saved.date,'2026-09-24');
 assert.equal(saved.title,'Test local event');
 await page.locator('[data-view=week]').click();await page.locator('.ws-slot').first().waitFor();
 await page.locator('.ws-slot').first().click();assert.equal(await page.locator('[name=time]').inputValue(),'08:00');
 await page.getByRole('button',{name:'Close event panel'}).click();
 await page.locator('[data-view=list]').click();await page.locator('.ws-list-row').waitFor();
 failFeed=true;await page.locator('[data-move="1"]').click();await page.locator('[data-retry]').waitFor();
 failFeed=false;await page.locator('[data-retry]').click();await page.locator('.ws-list-row').waitFor();
 await page.setViewportSize({width:390,height:844});await page.reload();await page.locator('.ws-list-row').waitFor();
 assert.equal(await page.locator('[data-view=list]').getAttribute('aria-pressed'),'true');
 // The services editor shares this client and formerly failed at the same helper.
 config.mode='services';config.rows=[{index:0,day:'Sunday',time:'9 am',note:'Worship'}];
 await page.unroute('https://workspace.test/**');
 await page.route('https://workspace.test/**',r=>r.fulfill({contentType:'text/html',body:`<form id="service-form"><div id="service-rows"></div><input id="service-json"><button id="save-services" disabled>Save</button></form><button id="add-service">Add</button><p id="service-error"></p><script id="workspace-data" type="application/json">${JSON.stringify(config)}</script><script>${WORKSPACE_CLIENT}</script>`}));
 await page.goto('https://workspace.test/services');assert.equal(await page.locator('#save-services').isEnabled(),true);
 await page.locator('#add-service').click();assert.equal(await page.locator('.ws-service').count(),2);
 // Google editing uses the same production bundling and a fake Google-backed API.
 const googleOut=path.join(dir,'google.mjs');
 await build({entryPoints:['admin/calendar-google-client.js'],bundle:true,format:'esm',keepNames:true,outfile:googleOut});
 const {GOOGLE_CALENDAR_CLIENT}=await import(pathToFileURL(googleOut));
 Object.assign(config,{mode:'calendar',googleEnabled:true,googleColors:[{id:'3',name:'Music'}],canNews:true});
 const gcal={...event,id:'g:occurrence',source:'gcal',googleCalendarId:'church@test',googleEventId:'occurrence',recurringEventId:'series'};
 const googleSaves=[];let failSave=true;
 await page.unroute('https://workspace.test/**');
 await page.route('https://workspace.test/**',async route=>{
  const url=new URL(route.request().url());
  if(url.pathname.endsWith('/connection'))return route.fulfill({json:{calendars:[{id:'church@test',name:'Church',writable:true}]}});
  if(url.pathname.endsWith('/feed'))return route.fulfill({json:{events:[gcal,event],categories:[],google:true}});
  if(url.pathname.endsWith('/event')&&route.request().method()==='GET')return route.fulfill({json:{event:{title:'Community meal',date:'2026-09-23',endDate:'2026-09-23',time:'18:00',endTime:'19:00',etag:'"live"',eventId:url.searchParams.get('eventId'),recurringEventId:url.searchParams.get('eventId')==='occurrence'?'series':'',recurrence:url.searchParams.get('eventId')==='series'?['RRULE:FREQ=WEEKLY']:[]}}});
  if(['/event','/create','/publish'].some(s=>url.pathname.endsWith(s))){googleSaves.push(route.request().postDataJSON());if(failSave){failSave=false;return route.fulfill({status:503,json:{error:'Google did not confirm the save. Retry.'}});}return route.fulfill({json:{saved:true}});}
  return route.fulfill({contentType:'text/html',body:`<!doctype html>${WORKSPACE_CSS}<aside class="sidebar">Admin navigation</aside><div id="workspace-calendar"></div><script id="workspace-data" type="application/json">${JSON.stringify(config)}</script><script>${GOOGLE_CALENDAR_CLIENT}</script><script>${WORKSPACE_CLIENT}</script>`});
 });
 await page.setViewportSize({width:1280,height:900});
 await page.goto('https://workspace.test/calendar-workspace');await page.locator('.ws-day').first().waitFor();
 await page.locator('[data-add="2026-09-24"]').click();
 await page.locator('#google-event-form [name=title]').fill('Choir practice');
 await page.locator('#google-event-form [name=colorId]').selectOption({label:'Music'});
 await page.locator('#google-event-form [name=repeat]').selectOption('WEEKLY');
 await page.getByRole('button',{name:'Save to Google Calendar'}).click();
 await page.getByText('Google did not confirm the save. Retry.',{exact:true}).waitFor();
 assert.equal(await page.locator('#google-event-form [name=title]').inputValue(),'Choir practice');
 await page.getByRole('button',{name:'Save to Google Calendar'}).click();await page.locator('#google-event-form').waitFor({state:'hidden'});await page.locator('.ws-day').first().waitFor();await page.getByText('Saved to Google Calendar.',{exact:true}).waitFor();
 assert.equal(googleSaves[0].colorId,'3');
 assert.equal(googleSaves[0].requestId,googleSaves[1].requestId,'failed save retry keeps the same identity');assert.equal(googleSaves[1].calendarId,'church@test');assert.equal(googleSaves[1].repeat,'WEEKLY');
 await page.locator('[data-event="g:occurrence"]').click();await page.getByRole('button',{name:'Edit entire series instead'}).click();
 await page.getByText('Editing the entire series.',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Save to Google Calendar'}).click();await page.locator('#google-event-form').waitFor({state:'hidden'});await page.locator('.ws-day').first().waitFor();await page.getByText('Saved to Google Calendar.',{exact:true}).waitFor();
 assert.equal(googleSaves.at(-1).eventId,'series');assert.equal(googleSaves.at(-1).etag,'"live"');
 await page.locator('[data-event="n:7"]').click();await page.getByRole('button',{name:'Publish / link to Google',exact:true}).click();
 await page.locator('[name=linkEventId]').selectOption('occurrence');await page.getByRole('button',{name:'Publish / link to Google',exact:true}).click();await page.locator('#google-event-form').waitFor({state:'hidden'});await page.locator('.ws-day').first().waitFor();await page.getByText('Saved to Google Calendar.',{exact:true}).waitFor();
 assert.equal(googleSaves.at(-1).sourceKey,'n:7');assert.equal(googleSaves.at(-1).linkEventId,'occurrence');
 await page.locator('#calendar-room').selectOption('Hall');assert.equal(await page.locator('[data-event]').count(),2);
 await page.emulateMedia({media:'print'});assert.equal(await page.locator('.sidebar').isVisible(),false);await page.locator('.ws-day').first().waitFor({state:'visible'});assert.equal(await page.locator('.ws-day').first().isVisible(),true);await page.emulateMedia({media:'screen'});
 // Print this view prints the calendar alone: one landscape page for a month, a busy day ending in "+N more".
 await page.locator('#calendar-room').selectOption('');
 const busy=Array.from({length:14},(_,i)=>({...event,id:'b:'+i,title:'Busy item '+i,start:'2026-09-16T'+String(8+i%12).padStart(2,'0')+':00:00',end:null}));
 await page.unroute('https://workspace.test/**');
 await page.route('https://workspace.test/**',r=>{const u=new URL(r.request().url());if(u.pathname.endsWith('/feed'))return r.fulfill({json:{events:busy,categories:[],google:true}});if(u.pathname.endsWith('/connection'))return r.fulfill({json:{calendars:[]}});return r.fulfill({contentType:'text/html',body:`<!doctype html>${WORKSPACE_CSS}<aside class="sidebar">Admin navigation</aside><div class="tlc-main"><main class="ws-wrap"><h1 class="page-title">Calendar &amp; events</h1><p id="intro">Click a date to add an event.</p><div id="workspace-calendar"></div></main></div><div class="tlc-k">Search every section</div><script id="workspace-data" type="application/json">${JSON.stringify(config)}</script><script>${GOOGLE_CALENDAR_CLIENT}</script><script>${WORKSPACE_CLIENT}</script>`});});
 await page.setViewportSize({width:989,height:749});
 await page.goto('https://workspace.test/calendar-workspace');await page.locator('.ws-day').first().waitFor();
 await page.evaluate(()=>{window.print=()=>{window.__printed=true;};});await page.locator('[data-print]').click();
 assert.equal(await page.evaluate(()=>window.__printed),true,'Print this view opens the print dialog');
 await page.emulateMedia({media:'print'});await page.waitForTimeout(100);
 for(const sel of ['.page-title','#intro','.tlc-k','[data-view=month]','#calendar-room'])assert.equal(await page.locator(sel).isVisible(),false,sel+' does not print');
 assert.equal(await page.locator('#workspace-calendar h2').first().isVisible(),true,'the month title prints');
 assert.match(await page.locator('.ws-more').first().textContent(),/^\+\d+ more$/,'a busy day says how many more it holds');
 const pdf=await page.pdf({preferCSSPageSize:true});
 assert.equal((pdf.toString('latin1').match(/\/Type\s*\/Page[^s]/g)||[]).length,1,'the month prints on one page');
 await page.emulateMedia({media:'screen'});await page.evaluate(()=>window.dispatchEvent(new Event('afterprint')));
 assert.equal(await page.locator('.ws-more').count(),0,'and the page is restored after printing');
 const sortable=[{...event,id:'n:1',title:'Zebra meeting',category:'meetings'},{...event,id:'g:2',source:'gcal',title:'Alpha choir',category:'music',start:'2026-09-24T18:00:00',end:'2026-09-24T19:00:00'}];
 await page.route('**/calendar-workspace/feed?**',r=>r.fulfill({json:{events:sortable,categories:[{key:'meetings',name:'Meetings'},{key:'music',name:'Music'}],google:true}}));
 await page.reload();await page.locator('.ws-day').first().waitFor();
 await page.locator('#calendar-sort').selectOption('title');await page.locator('.ws-list-row').first().waitFor();
 assert.deepEqual(await page.locator('.ws-list-row h3').allTextContents(),['Alpha choir','Zebra meeting']);
 await page.locator('#calendar-sort').selectOption('category');await page.locator('.ws-list-row').first().waitFor();
 assert.deepEqual(await page.locator('.ws-list-row h3').allTextContents(),['Zebra meeting','Alpha choir']);
 await page.locator('#calendar-category').selectOption('music');
 assert.deepEqual(await page.locator('.ws-list-row h3').allTextContents(),['Alpha choir']);
 await page.locator('#calendar-search').fill('missing');assert.equal(await page.locator('.ws-list-row').count(),0);
 assert.deepEqual(errors,[]);
 console.log('Bundled calendar and services browser interactions passed.');
} finally {await browser?.close();await rm(dir,{recursive:true,force:true});}
