// ── THE FOUR PAGES, IN THE REDESIGN'S LANGUAGE ───────────────────────────────
//
// /news, Home, Worship and Ministries, as block stacks. Hand-authored, which is
// the whole reason this file exists rather than a few more entries in
// admin/site-pages.js: that file is GENERATED by tools/extract-pages.mjs out of
// the hardcoded markup in public/index.html, and anything written into it by
// hand is gone the next time the extractor runs. The same argument already put
// NEWS_PAGE_SEED in the Worker; this is that decision applied to four pages
// instead of one, and somewhere better than a Worker.
//
// ⚠ WHAT THIS FILE REPLACES IS THE BLOCKS, AND ONLY THE BLOCKS. A page's title,
// address, menu placement and layout stay generated. Those are facts about the
// site's structure that the extractor gets right and that nobody should be
// maintaining in two places; the content is the part a designer authored.
//
// ⚠ AND IT LANDS IN THE DRAFT. Every seed in this repo does — `published_blocks`
// stays NULL, so the live site keeps rendering its hardcoded markup until
// somebody opens the page, reads the draft against the page it replaces, and
// presses Publish. That is not a formality here. These four are the most
// visited pages on the site, the language they are written in is new, and there
// are no photographs yet. Publishing is a decision somebody makes while
// watching, one page at a time.
//
// ⚠ NO TRAILING ARROWS ON LINK LABELS, anywhere below. Every label in the
// design handoff carries one; this repo has a CI check that forbids exactly
// that, added twice after Dinger said he did not want it. The layout is the
// design's. The glyph is not.
//
// ── ON THE PHOTOGRAPHS ───────────────────────────────────────────────────────
// There are none. The handoff says the design depends on about eight and that
// every picture in the mocks is an empty drop target. So every banner below has
// `photo: ''` and renders as a flat ink-navy field — a deliberate look rather
// than a hole, which is why the Photo banner draws no veil when there is no
// photograph to shade (a dark gradient over navy is what a picture that failed
// to load looks like). Dropping a photo in later is one click in the editor and
// changes nothing else.

// The calendar the church actually publishes — the main calendar plus the
// secondary one. Carried here rather than typed into the seed twice.
const CALENDAR_EMBED = 'https://calendar.google.com/calendar/embed'
  + '?src=calendar%40timothystl.org'
  + '&src=c_7f6d3db77b48c01af48592e21b2743d22fdf2b221d9d3c4e0c02680b73b89041%40group.calendar.google.com'
  + '&ctz=America%2FChicago&mode=MONTH&showTitle=0&showNav=1&showDate=1'
  + '&showPrint=0&showTabs=0&showCalendars=0&showTz=0&bgcolor=%23ffffff';

// The background indices from BG in admin/blocks.js. Named, because `bg: 6`
// twenty lines down tells nobody anything.
const PAPER = 4;
const WHITE = 5;
const INK = 6;
const GOLD = 7;
// And the inks that go with them.
const BODY_INK = 5;
const CREAM = 3;
const GOLD_INK = 6;

// Only the fields that are actually being decided are set. sanitizeBlocks()
// fills in every other default a real block needs, so a seed that lists
// `spaceAbove: 24` on every entry is twenty lines of noise hiding the two
// values that were chosen.

export const REDESIGN_BLOCKS = {
  // ── /news ─────────────────────────────────────────────────────────────────
  // The page the redesign was commissioned for. Andrew's brief was that it
  // "feels dead"; it was a navy page hero, two identical linen sections, a
  // single column of white cards and a calendar iframe.
  news: [
    {
      id: 'news-1b-1', type: 'photobanner',
      eyebrow: 'Happening next',
      title: 'There is always something next.',
      subtitle: 'Services, classes, the pantry, the market — everything the congregation is doing between now and Advent.',
      bannerHeight: 'tall', veil: 'medium', countdown: true, pulse: true,
      // Clay on News, per the handoff's per-page assignment.
      glow: 'clay',
      bg: INK, ink: CREAM, spaceAbove: 0, spaceBelow: 0,
    },
    // Self-filling, and it disappears entirely when nothing is coming up —
    // which is why it can sit here permanently without ever being an empty row.
    {
      id: 'news-1b-2', type: 'chips',
      title: 'Coming up', count: 5,
      bg: WHITE, ink: BODY_INK, spaceAbove: 0, spaceBelow: 0,
    },
    {
      id: 'news-1b-3', type: 'newsfeed',
      title: 'What’s going on',
      eyebrow: '',
      cols: 2, count: 4, photos: true,
      bg: WHITE, ink: BODY_INK, spaceAbove: 24, spaceBelow: 24,
    },
    // The archive as a band. Andrew asked in the /news editor for the most
    // recent letter open and the rest as a list rather than a column of
    // near-identical rows — this is that, laid out sideways.
    {
      id: 'news-1b-4', type: 'letter',
      title: 'The weekly letter',
      body: '<p>Pastor Dinger writes every week — what we are preaching, who needs prayer, and what is on the calendar.</p>',
      count: 5, signup: true,
      bg: INK, ink: CREAM, spaceAbove: 0, spaceBelow: 0,
    },
    {
      id: 'news-1b-5', type: 'calendar',
      eyebrow: 'The whole month',
      title: 'Church calendar',
      body: '<p>Every service, meeting and rehearsal. Add it to your own phone and it keeps itself up to date.</p>',
      url: CALENDAR_EMBED, embedHeight: 'm', subscribe: true,
      bg: WHITE, ink: BODY_INK, spaceAbove: 24, spaceBelow: 24,
    },
  ],

  // ── Home ──────────────────────────────────────────────────────────────────
  // ⚠ There is no email sign-up block at the foot of this stack, and the
  // design's Home ends with one. That band is site-wide CHROME — it renders on
  // all 28 pages, outside every page div, and is edited under
  // Menu → Appearance. A block here would be a second copy of it on the one
  // page that already has it, directly above itself.
  home: [
    {
      id: 'home-1b-1', type: 'photobanner',
      eyebrow: 'Lindenwood Park · St. Louis',
      title: 'Whoever you are, wherever you have been — you are welcome here.',
      subtitle: 'A congregation shaped by grace — not by what we have done for God, but by what God has done for us in Jesus Christ.',
      bannerHeight: 'tall', veil: 'medium', countdown: false, pulse: false,
      glow: 'gold',
      // The white card carrying the service times and the address. It reads the
      // church-details record, so the times are right on every page at once and
      // nobody retypes them here.
      card: 'right', cardShows: 'services', cardEyebrow: 'Join us Sunday',
      bg: INK, ink: CREAM, spaceAbove: 0, spaceBelow: 0,
    },
    {
      id: 'home-1b-2', type: 'quote',
      title: 'A diverse city church serving as a bold witness to the saving grace of God through Jesus Christ.',
      body: '<p>Timothy Lutheran is rooted in Lindenwood Park. We are Lutheran, which means we lead with grace — not a reward for the righteous but a gift for the broken. Every person who walks through our doors carries something. The gospel is strong enough to carry it with them.</p>',
      bg: PAPER, ink: BODY_INK, spaceAbove: 0, spaceBelow: 0,
    },
    // Two halves, so the sermon card and the news list sit side by side. Both
    // fill themselves, so this pair is correct on the day it is published and
    // stays correct with nobody editing it.
    {
      id: 'home-1b-3', type: 'sermon',
      title: 'This week', width: 'half',
      bg: WHITE, ink: BODY_INK, spaceAbove: 24, spaceBelow: 24,
    },
    {
      id: 'home-1b-4', type: 'news',
      title: 'What’s happening', count: 4, width: 'half',
      bg: WHITE, ink: BODY_INK, spaceAbove: 24, spaceBelow: 24,
    },
  ],

  // ── Worship ───────────────────────────────────────────────────────────────
  worship: [
    {
      id: 'worship-1b-1', type: 'photobanner',
      eyebrow: 'Sunday mornings',
      title: 'Worship at Timothy',
      subtitle: 'Two services every Sunday. Come as you are — we mean it.',
      bannerHeight: 'mid', veil: 'medium', countdown: false, pulse: false,
      glow: 'gold',
      bg: INK, ink: CREAM, spaceAbove: 0, spaceBelow: 0,
    },
    // The times set at display size, which is the design's whole argument for
    // this page: they are the reason somebody opened it.
    {
      id: 'worship-1b-2', type: 'servicetimes',
      title: '', layout: 'tiles',
      bg: WHITE, ink: BODY_INK, spaceAbove: 24, spaceBelow: 8,
    },
    {
      id: 'worship-1b-3', type: 'cardgrid',
      eyebrow: '',
      title: 'First time visiting?',
      subtitle: 'We want your first Sunday to be easy. Here is everything you need before you arrive.',
      cols: 2, logos: false, feature: false,
      bg: WHITE, ink: BODY_INK, spaceAbove: 8, spaceBelow: 24,
      items: [
        { title: 'Parking', body: '<p>Free in the lot on Ivanhoe, directly across from the church office. There is street parking on Fyler too.</p>' },
        { title: 'Kids & families', body: '<p>Children are welcome in worship at any age. Sunday School runs during the 10:45, and there is a nursery for infants.</p>' },
        { title: 'What to wear', body: '<p>From suits to shorts. Come as you are — what matters is that you showed up.</p>' },
        { title: 'Questions first?', body: '<p>Greeters are at the door before every service, or reach us at office@timothystl.org and (314) 781-8673.</p>' },
      ],
    },
    {
      id: 'worship-1b-4', type: 'textphoto',
      eyebrow: 'Music & sound',
      title: 'A soundscape as wide as grace',
      body: '<p>Organ and handbells, guitar and drums, an African choir, a hammer dulcimer, steel drums. Sometimes all of it in one service — because the grace we celebrate is that wide.</p>',
      side: 'right', split: '50',
      bg: INK, ink: CREAM, spaceAbove: 24, spaceBelow: 0,
    },
    // The two pills under it. Text + photo carries no buttons of its own, and
    // giving it some would be a second way for a button row to exist — the
    // Button bar is already that, and it sits on the same band.
    {
      id: 'worship-1b-5', type: 'buttons',
      bg: INK, ink: CREAM, spaceAbove: 0, spaceBelow: 24,
      items: [
        { title: 'Watch the live stream', url: 'https://www.youtube.com/timothystl' },
        { title: 'Music ministry', url: '/music' },
      ],
    },
  ],

  // ── Ministries ────────────────────────────────────────────────────────────
  ministries: [
    {
      id: 'min-1b-1', type: 'photobanner',
      eyebrow: 'Life at Timothy',
      title: 'Ministries',
      subtitle: 'Ways to connect, serve, grow and belong — nine of them, and room for one more.',
      bannerHeight: 'short', veil: 'medium', countdown: false, pulse: false,
      glow: 'gold',
      bg: INK, ink: CREAM, spaceAbove: 0, spaceBelow: 0,
    },
    {
      id: 'min-1b-2', type: 'cardgrid',
      title: '', subtitle: '',
      cols: 3,
      // Logos rather than photographs: these are wordmarks and roundels of
      // wildly different shapes, and cropping them to fill a card ruins at
      // least one. The featured first card is the Food Pantry, which is the
      // one the church most wants a stranger to find.
      logos: true, feature: true,
      bg: WHITE, ink: BODY_INK, spaceAbove: 24, spaceBelow: 8,
      items: [
        { img: '/images/ministries/food-pantry-thumb.webp', title: 'Food Pantry', body: '<p>Open monthly for members and neighbors. Sixty-eight households last month, served with practical care.</p>', linkLabel: 'Get details', url: '/foodpantry' },
        { img: '/images/ministries/wol-logo.webp', title: 'Word of Life Lutheran School', body: '<p>A Christ-centered school for our neighborhood — a high-quality program in an environment where Christ prevails.</p>', linkLabel: 'Learn more', url: '/wol' },
        { img: '/images/ministries/mdo-thumb.webp', title: 'Mother’s Day Out', body: '<p>Twenty years of caring childcare from birth through preschool. Small rooms, flexible scheduling, real community.</p>', linkLabel: 'Visit MDO', url: '/mdo' },
        { img: '/images/ministries/ss-logo.webp', title: 'Stephen Ministry', body: '<p>Trained caregivers who listen to the real pains of our members and community, and walk alongside people in hard seasons.</p>', linkLabel: 'Learn more', url: '/stephen' },
        { img: '/images/ministries/Bees-thumb.webp', title: 'Urban Beekeepers', body: '<p>Neighbors learning the art of beekeeping in the city — a joyful reminder that creation care is part of the calling.</p>', linkLabel: 'Learn more', url: '/bees' },
        { img: '/images/ministries/christmas-mkt-thumb.webp', title: 'Christmas Market', body: '<p>An annual gift to Lindenwood Park every December: shopping, fellowship, and a neighborhood in one room.</p>', linkLabel: 'Learn more', url: '/christmasmarket' },
        { img: '', title: 'Music Ministry', body: '<p>Organ, handbells, guitar, drums, African choir, hammer dulcimer, steel drums. Unique but familiar.</p>', linkLabel: 'Learn more', url: '/music' },
        { img: '', title: 'Youth & Family', body: '<p>Formation for children, confirmation for middle schoolers, community for parents at every stage.</p>', linkLabel: 'Explore', url: '/youthfamily' },
        { img: '/images/ministries/lwml.webp', title: 'LWML', body: '<p>Lutheran Women’s Missionary League — a community of women in mission for Christ. Rooted in Scripture, sent in service.</p>', linkLabel: 'Visit LWML', url: 'https://www.lwml.org' },
      ],
    },
    // The design's call-to-action band, which is the Button bar on gold — it
    // has carried an eyebrow, a heading and a rich description above its
    // buttons since v4.32.0. A separate `cta` type would have been a second
    // near-identical block to drift apart from this one.
    {
      id: 'min-1b-3', type: 'buttons',
      eyebrow: 'Get involved',
      title: 'Ready to put your hands to work?',
      body: '<p>From Sunday setup to the pantry to the Christmas Market — there is always something, and it is never only one kind of person doing it.</p>',
      bg: GOLD, ink: GOLD_INK, spaceAbove: 24, spaceBelow: 24,
      items: [{ title: 'See what is open', url: 'https://serve.timothystl.org' }],
    },
  ],
};

export const REDESIGN_PAGE_IDS = Object.keys(REDESIGN_BLOCKS);
