import assert from 'node:assert/strict';
import { serviceRows, serializeServiceRows, calendarInput, pageDependencies, safeWorkspaceReturn } from './workspace.js';
const original=' Sunday | 8:00 am | Traditional  \nWednesday | After supper | Bring a friend\nUnusual legacy wording | with | extra | fields\n\n';
assert.equal(serializeServiceRows(original,serviceRows(original)),original,'unchanged records retain exact text, whitespace, and legacy lines');
const edited=serviceRows(original);edited[0].time='8:30 am';assert.equal(serializeServiceRows(original,edited),'Sunday | 8:30 am | Traditional\nWednesday | After supper | Bring a friend\nUnusual legacy wording | with | extra | fields\n\n');
assert.throws(()=>serializeServiceRows(original,[edited[0],edited[0]]));
assert.throws(()=>serializeServiceRows('',[{index:null,day:'Sunday',time:'8|9',note:''}]));
assert.equal(safeWorkspaceReturn('//evil.test'),'/shared-content');assert.equal(safeWorkspaceReturn('/pages/home/overview'),'/pages/home/overview');
const event={title:'Board meeting',date:'2026-09-22',endDate:'2026-09-22',time:'19:00',endTime:'20:00',room:'',type:''};
assert.equal(calendarInput(event).local_event_time,'19:00');
assert.throws(()=>calendarInput({...event,date:'2026-02-30'}));
assert.throws(()=>calendarInput({...event,time:'19:00junk'}));
assert.throws(()=>calendarInput({...event,endTime:'18:00'}));
assert.equal(calendarInput({...event,endDate:'2026-09-23',endTime:'01:00'}).local_end_time,'01:00');
assert.equal(calendarInput({...event,allDay:true}).local_event_time,null);
assert.equal(calendarInput({...event,allDay:true}).local_end_time,null);
assert.throws(()=>calendarInput({...event,type:'__proto__'}));
const dep=blocks=>pageDependencies({id:'home',blocks:JSON.stringify(blocks),template:'standard'}).map(x=>x.key);
assert.ok(dep([{type:'servicetimes'}]).includes('services'));
assert.ok(dep([{type:'slideshow',card:'right',cardShows:'services'}]).includes('services'));
assert.ok(!dep([{type:'slideshow',card:'none',cardShows:'services'}]).includes('services'));
assert.ok(!dep([{type:'times',items:[{day:'Sunday',time:'8:00'}]}]).includes('services'),'page-owned times are not called shared');
assert.ok(!dep([{type:'countdown',newsId:'custom',customAt:'2026-10-01T10:00'}]).includes('countdown'));
assert.ok(dep([{type:'countdown',newsId:'4'}]).includes('countdown'));
assert.ok(pageDependencies({blocks:'[]',template:'sectionside'}).some(d=>d.key==='services'));
console.log('Workspace validation and content preservation passed.');
