import test from 'node:test';import assert from 'node:assert/strict';
import {cleanBlocks,cleanPilot,renderPilot} from './model.mjs';import {PAGE_SEEDS} from '../../admin/page-seeds.js';import {sanitizeBlocks,renderPage,newBlock,BLOCK_TYPE_KEYS} from '../../admin/blocks.js';
test('all existing seed content and IDs survive local save/reopen unchanged',()=>{for(const seed of Object.values(PAGE_SEEDS)){const before=sanitizeBlocks(seed);assert.deepEqual(cleanBlocks(JSON.parse(JSON.stringify(before))),before)}});
test('every existing block type survives round-trip',()=>{for(const t of BLOCK_TYPE_KEYS){const b=newBlock(t);assert.deepEqual(cleanBlocks([b]),[b])}});
test('untouched pages use identical production renderer output',()=>{for(const seed of Object.values(PAGE_SEEDS)){const bs=sanitizeBlocks(seed);assert.equal(renderPilot(bs,{data:{}}),renderPage(bs,{editing:true,withCss:true,data:{},slug:'foodpantry'}))}});
test('layout envelope preserves all block content and renders every ID exactly once',()=>{const before=sanitizeBlocks(PAGE_SEEDS.foodpantry),bs=structuredClone(before);bs[1].pilot={layout:{group:'a',column:0,ratio:63,reverse:true}};bs[2].pilot={layout:{group:'a',column:1,ratio:63,reverse:true}};const saved=cleanBlocks(JSON.parse(JSON.stringify(bs)));assert.deepEqual(saved.map(({pilot,...b})=>b),before);const html=renderPilot(saved);for(const b of before)assert.equal(html.split('data-id="'+b.id+'"').length-1,1);assert.match(html,/lp-reverse/);assert.match(html,/63fr/);});
test('reject unknown and duplicate blocks rather than silently discarding content',()=>{assert.throws(()=>cleanBlocks([{type:'future-block'}]));const b=newBlock('text');assert.throws(()=>cleanBlocks([b,b]))});
test('countdown URLs are sanitized; source references remain untouched',()=>{const b=newBlock('countdown',{newsId:'42'});b.pilot={countdown:{ending:'button',url:'javascript:alert(1)',buttonText:'Next',duration:90}};const saved=cleanBlocks([b])[0];assert.equal(saved.newsId,b.newsId);assert.equal(saved.pilot.countdown.url,'');assert.equal(saved.pilot.countdown.duration,90);});
test('fine layout and stamp values are bounded and valid linked buttons persist',()=>{const p=cleanPilot({head:999,stamp:{size:90,x:-3},countdown:{url:'https://timothystl.org/foodpantry',newTab:true}});assert.equal(p.head,80);assert.equal(p.stamp.size,30);assert.equal(p.stamp.x,0);assert.equal(p.countdown.url,'https://timothystl.org/foodpantry');assert.equal(p.countdown.newTab,true);});
test('overlay save/reopen preserves background and card blocks without duplication',()=>{
 const before=sanitizeBlocks(PAGE_SEEDS.foodpantry),bs=structuredClone(before);
 for(let i=0;i<2;i++)bs[i].pilot={layout:{group:'overlay',column:i,mode:'overlay',position:'left',placement:'edge',overlap:80,cardWidth:45,cardColor:'#ffffff'}};
 const saved=cleanBlocks(JSON.parse(JSON.stringify(bs))),html=renderPilot(saved);
 assert.deepEqual(saved.map(({pilot,...b})=>b),before);
 for(const b of before)assert.equal(html.split('data-id="'+b.id+'"').length-1,1);
 assert.match(html,/lp-overlay--left lp-overlay--edge/);assert.match(html,/Add card content/);
 assert.doesNotMatch(html,/class="lp-divider"/);
 const preview=renderPilot(saved,{editing:false});assert.doesNotMatch(preview,/Add card content/);
 const p=cleanPilot({layout:{mode:'overlay',overlap:999,cardColor:'red;position:fixed'}});
 assert.equal(p.layout.overlap,160);assert.equal(p.layout.cardColor,'#ffffff');
});
