import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';
import {blocksClientConfig,editorPhoneCss,newBlock,blockDomId} from '../../admin/blocks.js';
import {PAGE_SEEDS} from '../../admin/page-seeds.js';import {LINKS_JS} from '../../admin/links.js';import {TINYMCE_HEAD} from '../../admin/db.js';import {churchInstant} from '../../admin/when.js';import {cleanBlocks,renderPilot} from './model.mjs';
const here=path.dirname(fileURLToPath(import.meta.url)),repo=path.resolve(here,'../..'),storage=path.resolve(process.env.PILOT_STORAGE||path.join(here,'.local')),port=Number(process.env.PORT||4320);fs.mkdirSync(storage,{recursive:true});
const file=path.join(storage,'draft.json');const tomorrow=new Date(Date.now()+86400000*12).toISOString().slice(0,10);
const seed=()=>{const b=cleanBlocks(PAGE_SEEDS.foodpantry);b[0].heroColor='parchment';b[0].pilot={head:44,spaceAbove:24,spaceBelow:24};const photo=newBlock('textphoto',{title:'Neighbors helping neighbors',body:'<p>Sample layout using an image already in the website repository.</p>',photo:'/images/ministries/food-pantry.webp',photoAlt:'Food pantry image from the website media collection',side:'above',spaceAbove:24,spaceBelow:24});photo.pilot={layout:{group:'pantry-example',column:0,ratio:62,reverse:false}};const cd=newBlock('countdown',{newsId:'901',stamp:'All are welcome',bg:1,title:'',spaceAbove:24,spaceBelow:24});cd.pilot={layout:{group:'pantry-example',column:1,ratio:62,reverse:false},stamp:{shape:'badge',x:70,y:2,size:13,mobileSize:11,rotation:0,visibility:'always'},countdown:{layout:'tiles',seconds:false,ending:'button',duration:120,buttonText:'See the next pantry date',url:'/foodpantry',newTab:false,nowText:'Join us today.',endText:'Thank you for coming.'},spaceAbove:60,spaceBelow:30};b.splice(1,0,photo,cd);return cleanBlocks(b)};
let blocks=fs.existsSync(file)?cleanBlocks(JSON.parse(fs.readFileSync(file))):seed(),sections=[],media=[{id:1,filename:'food-pantry.webp',kind:'photo',url:'/images/ministries/food-pantry.webp',thumb_url:'/images/ministries/food-pantry-thumb.webp',alt:'Food pantry image from the website media collection',meta:'Repository image'}];
const data={settings:{},services:[],staff:[],partners:[],news:[{id:901,title:'Pantry morning · sample event',event_date:tomorrow}],eventsById:{}};
const resolved=bs=>bs.map(b=>{const c=structuredClone(b);if(c.pilot?.stamp){const s=c.pilot.stamp;for(const k of ['from','until'])if(/^\d{4}-\d\d-\d\dT\d\d:\d\d$/.test(s[k]))s[k+'Instant']=churchInstant(s[k].slice(0,10),s[k].slice(11,16));}return c});
const persist=()=>{const tmp=file+'.tmp';fs.writeFileSync(tmp,JSON.stringify(blocks,null,2));fs.renameSync(tmp,file)};
const html=()=>fs.readFileSync(path.join(repo,'admin/ministry-editor.html'),'utf8').replace(/<link[^>]*>/g,'').replace('/*TLCB_EDITOR_CSS*/',editorPhoneCss()).replace('/*TLCB_LINKS_JS*/',LINKS_JS).replace('<!--TLCB_TINYMCE-->',TINYMCE_HEAD+'<link rel="stylesheet" href="/pilot.css"><script src="/runtime.js"></script>').replace('paletteOpen: true','paletteOpen: false').replace("var WIDTHS = { desktop: 900", "var WIDTHS = { desktop: 1080").replace('boot();',fs.readFileSync(path.join(here,'editor-extension.js'),'utf8')+'\nboot().then(lpBoot);');
const server=http.createServer(async(req,res)=>{try{
 if(!['127.0.0.1:'+port,'localhost:'+port].includes(req.headers.host)){res.writeHead(403);return res.end('Local pilot only')}
 if(req.headers.origin&&!['http://127.0.0.1:'+port,'http://localhost:'+port].includes(req.headers.origin)){res.writeHead(403);return res.end('Origin not allowed')}
 res.setHeader('Content-Security-Policy',"default-src 'self' data: blob:; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; connect-src 'self'; form-action 'none'; frame-src 'none'; base-uri 'none'");
 const p=new URL(req.url,'http://localhost').pathname;const json=(x,status=200)=>{res.writeHead(status,{'Content-Type':'application/json'});res.end(JSON.stringify(x))};let body={};if(req.method==='POST'){let chunks=[],size=0;for await(const c of req){size+=c.length;if(size>12*1024*1024)throw Error('File is too large');chunks.push(c)}const raw=Buffer.concat(chunks);if((req.headers['content-type']||'').includes('multipart/form-data')){if(p!=='/api/upload-image')return json({error:'Document uploads are not connected in this local pilot.'},400);const f=await new Request('http://localhost',{method:'POST',headers:{'content-type':req.headers['content-type']},body:raw}).formData(),upload=f.get('file')||f.get('image');if(!upload||!['image/jpeg','image/png','image/webp'].includes(upload.type))return json({error:'Choose a JPEG, PNG or WebP image.'},400);const name='upload-'+crypto.randomUUID()+'.'+({'image/jpeg':'jpg','image/png':'png','image/webp':'webp'}[upload.type]);fs.writeFileSync(path.join(storage,name),Buffer.from(await upload.arrayBuffer()));return json({url:'/uploads/'+name,location:'/uploads/'+name})}body=JSON.parse(raw.toString()||'{}')}
 if(p==='/pilot/reset'&&req.method==='POST'){blocks=seed();persist();return json({ok:true})}
 if(p==='/pages/api/page/foodpantry'&&req.method==='GET')return json({page:{title:'Food Pantry · pilot',status:'draft',blocks:resolved(blocks),path:'/foodpantry',published_count:0,settings:{title:'Food Pantry · pilot',slug:'foodpantry',template:'standard',in_menu:0}},config:blocksClientConfig(data),html:renderPilot(blocks,{data}),pages:[{id:'foodpantry',title:'Food Pantry · pilot',path:'/foodpantry'}],media,linkTargets:[{path:'/foodpantry',title:'Food Pantry',kind:'page'}],role:'office'});
 if(p==='/pages/api/render'){const bs=cleanBlocks(body.blocks);return json({blocks:resolved(bs),html:renderPilot(bs,{data})})}
 if(p==='/pages/api/new-block')return json({block:newBlock(body.type)});
 if(p==='/pages/api/page/foodpantry/draft'){const next=cleanBlocks(body.blocks);blocks=next;persist();return json({status:'draft'})}
 if(p==='/pages/api/media'){if(req.method==='POST'){const item={...body,id:media.length+1};media.push(item);return json({item})}return json({media})}
 if(p==='/pages/api/sections'){if(req.method==='POST'){const s={id:sections.length+1,name:String(body.name||''),blocks:cleanBlocks(body.blocks)};sections.push(s);return json({ok:true,section:s})}return json({sections:sections.map(s=>({...s,count:s.blocks.length}))})}
 if(/^\/pages\/api\/sections\/\d+$/.test(p))return json({blocks:sections.find(s=>s.id===+p.split('/').at(-1))?.blocks||[]});
 if(p.startsWith('/pages/api')||p.startsWith('/api/'))return json({error:'This operation is not connected in the local pilot. Production is untouched.'},400);
 if(p==='/preview'||p==='/foodpantry'){res.setHeader('Content-Type','text/html');const js=JSON.stringify(resolved(blocks)).replace(/</g,'\\u003c');return res.end('<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/pilot.css"><style>body{margin:0;background:#fbf8f3}.preview{max-width:1080px;margin:20px auto}nav{font:13px system-ui;padding:16px;background:#e6efed}</style><nav>LOCAL PREVIEW · Sample content · <a href="/pages/foodpantry/edit">Back to editor</a></nav><main class="preview">'+renderPilot(blocks,{editing:false,data}).replace(/<script>[\s\S]*?<\/script>/g,'')+'</main><script src="/runtime.js"></script><script>const blocks='+js+';function paint(){pilotDecorate(document,blocks)}paint();setInterval(paint,1000)</script>')}
 if(p==='/'||p==='/pages/foodpantry/edit'){res.setHeader('Content-Type','text/html');return res.end(html())}
 let filePath;if(p.startsWith('/assets/tinymce/7.9.3/'))filePath=path.join(repo,'admin/vendor/tinymce',p.slice('/assets/tinymce/7.9.3/'.length));else if(p.startsWith('/images/'))filePath=path.join(repo,'public',p);else if(p.startsWith('/uploads/'))filePath=path.join(storage,path.basename(p));else if(['/pilot.css','/runtime.js'].includes(p))filePath=path.join(here,p);if(!filePath||!fs.existsSync(filePath)||!fs.statSync(filePath).isFile()){res.writeHead(404);return res.end('Not available in local pilot')}
 res.setHeader('Content-Type',({'js':'text/javascript','css':'text/css','webp':'image/webp','png':'image/png','jpg':'image/jpeg','woff2':'font/woff2'}[filePath.split('.').at(-1)]||'application/octet-stream'));res.end(fs.readFileSync(filePath));
 }catch(e){res.writeHead(400,{'Content-Type':'application/json'});res.end(JSON.stringify({error:e.message}))}});
server.listen(port,'127.0.0.1',()=>console.log('Visual editor pilot: http://127.0.0.1:'+port+'/pages/foodpantry/edit'));
